name: Validate PR

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'supplements/**'
      - 'schemas/**'
      - 'vocab/**'
      - 'scripts/validate.ts'

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run validation
        id: validate
        run: |
          echo "Running validation..."
          if npm run validate > validation_output.txt 2>&1; then
            echo "validation_status=success" >> $GITHUB_OUTPUT
            echo "Validation passed ✅"
          else
            echo "validation_status=failed" >> $GITHUB_OUTPUT
            echo "Validation failed ❌"
          fi
          
          # Capture the output for commenting
          echo "validation_output<<EOF" >> $GITHUB_OUTPUT
          cat validation_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Comment on PR - Success
        if: steps.validate.outputs.validation_status == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `## ✅ Validation Passed
            
            All supplement data files are valid and follow the required schemas.
            
            <details>
            <summary>Validation Output</summary>
            
            \`\`\`
            ${{ steps.validate.outputs.validation_output }}
            \`\`\`
            
            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
      
      - name: Comment on PR - Failure
        if: steps.validate.outputs.validation_status == 'failed'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `## ❌ Validation Failed
            
            Some supplement data files have validation errors that need to be fixed:
            
            \`\`\`
            ${{ steps.validate.outputs.validation_output }}
            \`\`\`
            
            Please review the errors above and fix them before merging this PR.
            
            ### Common fixes:
            - Check that all required fields are present
            - Verify effect/biomarker names exist in vocabulary files
            - Ensure DOIs are valid and accessible
            - Check file naming conventions match the content`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
      
      - name: Fail the job if validation failed
        if: steps.validate.outputs.validation_status == 'failed'
        run: exit 1